### ISSUE TITLE
remove your auth token from the code

### ISSUE THREAD

**Issue by Adwaith-Rajesh** [Rishi-Ratan-Pandey/Gui-Reminder-App#1]
your Twilio auth token is visible. Have revoked it. ?

**Comment by RishiRatanPandey** [comment]
okay hiding the auth token.

**Comment by RishiRatanPandey** [comment]
Hi,@Adwaith-Rajesh Can You Try Our Reminder App If Yes Then Reply Yes But The App In Development Stage,so wait some days till the app is completed.
